# Welcome to Jekyll!
#

# Site settings
title: Code for Infrastructure
description: |
  A collection of resources and
  datasets available for use
  by Code for America Brigades
owner: Code for San Francisco
first_published: 2016 # if migrating another site, the year of your first publish
email: infrastructure@codeforsanfrancisco.org
baseurl: "/infrastructure" # the subpath of your site, e.g. /blog
url: "http://codeforsanfrancisco.org" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/sfbrigade
  github: https://github.com/sfbrigade
  # linkedin-square: https://linkedin.com/in/sfbrigade
  # facebook-official: https://facebook.com/sfbrigade
  # google-plus-square: https://plus.google.com/u/0/+sfbrigade
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
